module.exports = {
	OOPS_ERROR : "Oops!! Something went wrong.",
	REQUEST_OK : "The request is OK",
	AUTH_FAIL : "Authentication failed",
	INVALID_FORMAT : "Invalid format",
	INVALID_PARAMETER : "Invalid parameters",
	SUCCESS_UPDATE_PROFILE : "You have successfully updated your profile.",
	INVALID_STATE_ID : "Invalid State Id",
	DATE_ERROR : "Either start date is greater than end date or end date is greater than current date",
	INVALID_LINKEDIN_LINK : 'Please enter a valid LinkedIn link',
	INVALID_AMT : "Either minimum or maximum amount is not valid",
	INVALID_EMP_ID : "Invalid employment type id",
	UPLOAD_ERROR : "Unable to upload",
	INVALID_FILE_FORMAT : "Unsupported file format",
	FILE_SIZE_ERROR : "File size exceeds the limit",
	INVALID_CREDENTIALS : 'Invalid User Credentials',
	INVALID_PASS_FORMAT : "Password format is not correct",
	INVALID_EMAIL_FORMAT : "Email format is not correct",
	ENTER_EMAIL : "Please enter your email address",
	ENTER_PASSWORD : "Please enter your password",
	MISMATCH_PASS_CONFPASS : "Password does not match the confirm password",
	INVALID_EMAIL_ADD : "Please enter a valid email address",
	EMAIL_DOESNOT_EXIST : "That email address does not exist in our system",
	EXPIRED_LINK : "The link has been expired",
	INVALID_LINK : "Invalid link or link has been expired",
	SUCCESS_RESET_PASS : "You have successfully reset your password.",
	EMAIL_ALREADY_EXIST : "Email already exists",
	SENT_RESET_EMAIL : "We have send you Reset password link on your email.",
	CURRPASS_DOESNOT_EXIST : 'Your current password does not match our records.',
	SENT_CONTACTUS_MAIL : "The Legably team sent you a message.",
	ENTER_CURR_PASS : 'Please enter your current password',
	ENTER_NEW_PASS : 'Please enter your new password',
	ENTER_RETYPE_PASS : 'Please enter your retype new password',
	PASS_NOT_MATCH : 'Passwords do not match',
	INVALID_PASS_LENGTH : 'A valid password must be at least 8 characters long',
	INVALID_BAR_LENGTH : 'Bar registration number cannot be more than 15 digits',
	INVALID_SINGLE_CHAR_PASS : 'The password can not consist of single characters, i.e. "11111111" or "aaaaaaaa"',
	INVALID_CONSECUTIVE_PASS : 'The password can not consist of consecutive characters, i.e. "12345678" or "abcdefgh"',
	ENTER_FIRST_NAME : 'Please enter your first name',
	ENTER_LAST_NAME : 'Please enter your last name',
	ENTER_SUBJECT : 'Please enter your subject',
	ENTER_MESSAGE : 'Please enter your message',
	INVALID_FIRST_NAME_FORMAT : 'First Name should contain only alphabetic characters',
	INVALID_FIRST_NAME_LENGTH : 'First Name must be less than 50 characters',
	INVALID_LAST_NAME_FORMAT : 'Last Name should contain only alphabetic characters',
	INVALID_LAST_NAME_LENGTH : 'Last Name must be less than 50 characters',
	INVALID_SUB_LENGTH : 'Subject must be less than 50 characters',
	INVALID_MESSAGE_LENGTH : 'Message must be 1000 characters or less',
	CHECKBOX_ERROR : 'Please click the checkbox to verify',
	CONTACTUS_SUCCESS_MAIL_MESSAGE : "Thanks! Your message has been sent. We'll get back to you as soon as possible.",
	ENTER_RETYPE_PASSWORD : 'Please enter your retype password',
	TERM_SERV_ERROR : "Please click here to accept Legably's Terms of Service",
	FILE_COUNT_ERROR : "You can upload only one file",
	INVALID_LAWYER_HEADLINE_LENGTH : 'My Headline must be less than 150 characters',
	INVALID_ABOUT_ME_LENGTH : 'About Me must be less than 700 characters',
	ENTER_PRACTICE_AREA : 'Please enter your practice area',
	ENTER_STREET_ADD : 'Please enter your street address',
	INVALID_CITY_NAME : 'Please enter valid city name',
	ENTER_CITY : 'Please enter your city',
	ENTER_STATE : 'Please enter your state',
	ENTER_ZIPCODE : 'Please enter zip code',
	INVALID_PHONE_NO : 'Please enter valid mobile number',
	ENTER_PHONE_NO : 'Please enter your mobile number',
	ENTER_SCHOOL : 'Please enter your school',
	ENTER_DEGREE : 'Please enter your degree',
	ENTER_YEAR : 'Please enter your graduated year',
	ENTER_BAR_SKILL : 'Please enter skills',
	INVALID_ADD_INFO_LENGTH : 'Additional Information must be less than 250 characters',
	ENTER_BAR_NO : 'Please enter your bar registration number',
	ONLY_NUMERIC_ERROR : "Please enter numeric values only",
	INVALID_ZIPCODE : 'Zip Code should be numeric only and cannot exceed 5 digits',
	INVALID_YEAR : "Please enter a valid year",
	INVALID_YEAR_RANGE : "Year should be in range 1920 to current year",
	INVALID_COMPANY_NAME_LENGTH : 'Company name must be less than 100 characters',
	GREATER_START_DATE_ERROR : 'Start date is greater than end Date',
	INVALID_DATE : 'Please enter a valid date',
	INVALID_FIRSTNAME : 'Please enter a valid First Name',
	INVALID_LASTNAME : 'Please enter a valid Last Name',
	INVALID_URL : 'Please enter a valid website url',
	INVALID_ESTIMATED_DATE : "Estimated start date should be greater than or equal to today's date.",
	INVALID_HOUR_TYPE_ID : 'Invalid hour type id',
	SUBTOTAL_ERROR : "Sub total amount calculation is not correct",
	TOTAL_AMT_ERROR : "Total amount calculation is not correct",
	SUCCESS_POST_JOB : "You have successfully posted a job.",
	NO_RECORD_FOUND : "No record found",
	INVALID_DUE_DATE : "Due date should be greater than or equal to today's date.",
	IMAGE_SIZE_ERROR : "Image size should not exceed 10MB",
	RESUME_SIZE_ERROR : "File size should not exceed 3MB",
	ENTER_LOCATION : "Please select state",
	POPUP_MSG : 'The information you have entered on this page may not have been saved. Are you sure you want to leave? ',
	IE_MSG : "For the best experience, please use Legably in Google Chrome or Mozilla Firefox or Safari.",
	NEGATIVE_VAL_ERROR : "Please enter value greater than zero."

}